apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: kubevision
  region: us-east-1

iam:
  serviceRoleARN: arn:aws:iam::154514599060:role/LabRole

nodeGroups:
  - name: ng-1
    instanceType: t2.large
    desiredCapacity: 1
    volumeSize: 50
    iam:
      instanceRoleARN: arn:aws:iam::154514599060:role/LabRole